server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/rms
spring.datasource.username=root
spring.datasource.password=anshul@9009

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.thymeleaf.cache=false



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anshulrathore9009@gmail.com
spring.mail.password=evsq sqye hlsb jrcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



